sudo: required
services:
  - docker

before_install:
  - docker build -t dreddko/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dreddko/react-test npm test -- --coverage

after_success:
  - docker build -t dreddko/fib-client ./client
  - docker build -t dreddko/fib-nginx ./nginx
  - docker build -t dreddko/fib-server ./server
  - docker build -t dreddko/fib-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push dreddko/fib-client
  - docker push dreddko/fib-nginx
  - docker push dreddko/fib-server
  - docker push dreddko/fib-worker
